Added inventory notch and check, HP calculations, and game over condition to penguin and final boss

diff --git a/entrance/.rift/arena/pit/nyarlathotep b/entrance/.rift/arena/pit/nyarlathotep
--- a/entrance/.rift/arena/pit/nyarlathotep
+++ b/entrance/.rift/arena/pit/nyarlathotep
@@ -45,6 +45,33 @@ if [[ -e ../../.bless ]]; then
     resolve
 }
 
+notch () {
+    local list=$1
+    shift
+    local item=$1
+
+    return `sed -e "s/\b${item}\b//g; s/,,//g" <<< $list`
+}
+
+gameover () {
+    curr=`basename $PWD`
+    while [ "$curr" != "entrance" ]; do
+        pushd .. &> /dev/null
+        dirs -c
+        curr=`basename $PWD`
+    done
+    unset I
+    unset HP
+    $SHELL
+}
+
+flee () {
+    echo "You turn to flee but find that you cannot."
+    echo "You spend 1000 years as a mindless servant to the crawling chaos."
+    echo "When you awaken, you may attempt to fight for your liberation."
+    printf "\n"
+
+}
 resolve() {
     if [[ $MONSTER -eq $NUM ]]; then
 	echo "You dodge an attack, but you miss your mark as a result."
@@ -55,12 +82,12 @@ resolve() {
     if [[ $MONSTER -lt $NUM ]]; then
        echo "A hit! A palpable hit!"
        echo "You have vanquished the elder god of chaos!"
-       echo "\#\!/bin/sh" > treasure
+       echo '#!/bin/sh' > treasure
        echo "echo 'You have found a lock of the **hair** of a god!'" > treasure
        echo "echo 'Add it to your inventory.'" >> treasure
        chmod +x treasure
-       echo "\#\!/bin/sh" > platinum
-       echo 'You have found an enchanted *bracelet* of chaotic necromancy!'" >> platinum
+       echo '#!/bin/sh' > platinum
+       echo 'You have found an enchanted *bracelet* of chaotic necromancy!' >> platinum
        echo " You have reached the end of the game." > end
        echo " You know enough Bash now to use it for every day activities." >> end
        echo " Practice makes perfect, so be sure to use it often. " >> end
@@ -71,11 +98,22 @@ resolve() {
        echo "echo 'Add it to your inventory.'" >> platinum
        chmod +x platinum
     else
-	echo "Your sword swings harmlessly through the air."
-	echo "You take 10 points damage from your foe. Deduct this from your HP."
-	echo 'let "HP=HP-10"'
-	printf "\n"
-	roll
+    	echo "Your sword swings harmlessly through the air."
+    	echo "You take 10 points damage from your foe. Deduct this from your HP."
+    	echo 'let "HP=HP-10"'
+        let HP=HP-10
+        export HP
+        if [ "$HP" -le 0 ]; then
+            echo "The elder god of chaos consumes your body and soul."
+            echo
+            echo "You have been slain."
+            echo
+            echo "GAME OVER!"
+            gameover
+            exit 1
+        fi
+	    printf "\n"
+	    roll
     fi
 }
 
@@ -86,13 +124,16 @@ echo "Are you armed? y/n"
 read RESP
 
 if [ $RESP = "y" -o $RESP = "Y" ];then
-    roll
-    resolve
+    if grep -Po "sword" <<< $I; then
+        roll
+        resolve
+    else
+        echo "Oh, no!  You have lost your blade!"
+        echo "Nyarlathotep, the elder god of chaos, senses your weakness."
+        echo
+        flee
 else
-    echo "You turn to flee but find that you cannot."
-    echo "You spend 1000 years as a mindless servant to the crawling chaos."
-    echo "When you awaken, you may attempt to fight for your liberation."
-    printf "\n"
+    flee
 fi
 printf "\n"
 
